# Generated by Django 2.2 on 2019-05-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
